"""AdminInspectionChanres

Revision ID: 03498d10f94d
Revises: d1026e0f7f14
Create Date: 2026-08-29 16:04:36.458539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03498d10f94d'
down_revision: Union[str, Sequence[str], None] = 'd1026e0f7f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_inspection_cases', sa.Column('case_name', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_inspection_cases', 'case_name')
    # ### end Alembic commands ###
