"""update on schemas and others related to previous updates 1Aug10:48AM

Revision ID: 03ef231c2316
Revises: e90f0b95bd20
Create Date: 2026-08-01 10:48:35.650365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ef231c2316'
down_revision: Union[str, Sequence[str], None] = 'e90f0b95bd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
