"""1Aug1:38pm

Revision ID: 07b94c3d9c34
Revises: f5ff6f1bf596
Create Date: 2026-08-01 13:38:43.163677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b94c3d9c34'
down_revision: Union[str, Sequence[str], None] = 'f5ff6f1bf596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
