"""7_26_8_22pm

Revision ID: 131872f1c9f4
Revises: 0724df36be4c
Create Date: 2026-07-26 20:23:27.121362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131872f1c9f4'
down_revision: Union[str, Sequence[str], None] = '0724df36be4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('station_fee_rules_to_station_id_fkey'), 'station_fee_rules', type_='foreignkey')
    op.drop_constraint(op.f('station_fee_rules_from_station_id_fkey'), 'station_fee_rules', type_='foreignkey')
    op.create_foreign_key(None, 'station_fee_rules', 'route_stations', ['from_station_id'], ['id'])
    op.create_foreign_key(None, 'station_fee_rules', 'route_stations', ['to_station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_fee_rules', type_='foreignkey')
    op.drop_constraint(None, 'station_fee_rules', type_='foreignkey')
    op.create_foreign_key(op.f('station_fee_rules_from_station_id_fkey'), 'station_fee_rules', 'stations', ['from_station_id'], ['id'])
    op.create_foreign_key(op.f('station_fee_rules_to_station_id_fkey'), 'station_fee_rules', 'stations', ['to_station_id'], ['id'])
    # ### end Alembic commands ###
