"""8Aug10:53am

Revision ID: 1e004a258735
Revises: 735d8b47c867
Create Date: 2026-08-08 11:00:27.100275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e004a258735'
down_revision: Union[str, Sequence[str], None] = '735d8b47c867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('translation_used', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('chat_messages', sa.Column('language', sa.String(length=20), nullable=True))
    op.alter_column('chat_messages', 'content_burmese',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_column('chat_messages', 'confidence_score')
    op.drop_column('chat_messages', 'updated_at')
    op.drop_column('chat_messages', 'contexts_used')
    op.drop_column('document_chunks', 'english_embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('english_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('contexts_used', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_messages', 'content_burmese',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('chat_messages', 'language')
    op.drop_column('chat_messages', 'llm_model')
    op.drop_column('chat_messages', 'translation_used')
    # ### end Alembic commands ###
