"""23AugStationALTrainStopRelatedUpdate

Revision ID: 2d89ce5b0e0f
Revises: 39e9bd733a45
Create Date: 2026-08-23 16:10:07.041995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d89ce5b0e0f'
down_revision: Union[str, Sequence[str], None] = '39e9bd733a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bookings_schedule_id'), 'bookings', ['schedule_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'schedules', ['schedule_id'], ['id'], ondelete='RESTRICT')
    op.add_column('location_history', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_location_history_schedule_id'), 'location_history', ['schedule_id'], unique=False)
    op.create_index('ix_location_history_schedule_timestamp', 'location_history', ['schedule_id', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'location_history', 'schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('station_arrival_logs', 'schedule_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_station_arrival_logs_schedule_date'), 'station_arrival_logs', ['schedule_date'], unique=False)
    op.create_index(op.f('ix_station_arrival_logs_schedule_id'), 'station_arrival_logs', ['schedule_id'], unique=False)
    op.create_index('ix_station_arrival_logs_schedule_station', 'station_arrival_logs', ['schedule_id', 'route_station_id'], unique=False)
    op.create_unique_constraint('uq_station_arrival_logs_schedule_station', 'station_arrival_logs', ['schedule_id', 'route_station_id'])
    op.create_index(op.f('ix_train_stops_route_station_id'), 'train_stops', ['route_station_id'], unique=False)
    op.create_index(op.f('ix_train_stops_train_id'), 'train_stops', ['train_id'], unique=False)
    op.create_unique_constraint('uq_train_stops_train_route_station', 'train_stops', ['train_id', 'route_station_id'])
    op.drop_column('train_stops', 'actual_departure_time')
    op.drop_column('train_stops', 'status')
    op.drop_column('train_stops', 'actual_arrival_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_stops', sa.Column('actual_arrival_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('train_stops', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('train_stops', sa.Column('actual_departure_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_train_stops_train_route_station', 'train_stops', type_='unique')
    op.drop_index(op.f('ix_train_stops_train_id'), table_name='train_stops')
    op.drop_index(op.f('ix_train_stops_route_station_id'), table_name='train_stops')
    op.drop_constraint('uq_station_arrival_logs_schedule_station', 'station_arrival_logs', type_='unique')
    op.drop_index('ix_station_arrival_logs_schedule_station', table_name='station_arrival_logs')
    op.drop_index(op.f('ix_station_arrival_logs_schedule_id'), table_name='station_arrival_logs')
    op.drop_index(op.f('ix_station_arrival_logs_schedule_date'), table_name='station_arrival_logs')
    op.alter_column('station_arrival_logs', 'schedule_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'location_history', type_='foreignkey')
    op.drop_index('ix_location_history_schedule_timestamp', table_name='location_history')
    op.drop_index(op.f('ix_location_history_schedule_id'), table_name='location_history')
    op.drop_column('location_history', 'schedule_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_schedule_id'), table_name='bookings')
    op.drop_column('bookings', 'schedule_id')
    # ### end Alembic commands ###
