"""changed schedule(arrival date, overnight)

Revision ID: 2f3749d863a0
Revises: 391d7b39b750
Create Date: 2026-07-31 16:46:26.673721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3749d863a0'
down_revision: Union[str, Sequence[str], None] = '391d7b39b750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('is_overnight', sa.Boolean(), nullable=False))
    op.add_column('schedules', sa.Column('arrival_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'arrival_date')
    op.drop_column('schedules', 'is_overnight')
    # ### end Alembic commands ###
