"""added train rider models 1Aug8:41pm

Revision ID: 35fa8ae73753
Revises: c8e3a1486f93
Create Date: 2026-08-01 20:41:43.920370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fa8ae73753'
down_revision: Union[str, Sequence[str], None] = 'c8e3a1486f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
