"""add TRACK_ENGINEER to staffrole enum

Revision ID: 4f7a2d91c6e8
Revises: b00c3078197d
Create Date: 2026-08-25

This migration is intentionally separate from the autogenerated
Track Engineer tables migration because Alembic autogenerate does not
reliably detect new values added to an existing PostgreSQL ENUM.
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4f7a2d91c6e8"
down_revision: Union[str, Sequence[str], None] = "b00c3078197d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add TRACK_ENGINEER to PostgreSQL staffrole enum."""
    op.execute(
        "ALTER TYPE staffrole ADD VALUE IF NOT EXISTS 'TRACK_ENGINEER'"
    )


def downgrade() -> None:
    """
    PostgreSQL does not support DROP VALUE for an enum directly.

    Keep TRACK_ENGINEER in the enum on downgrade. This is safer than rebuilding
    the staffrole enum and potentially invalidating existing staff rows.
    """
    pass