"""add stations, fees, and train_classes tables

Revision ID: 61e6be0597a4
Revises: cac93c575368
Create Date: 2026-07-26 16:11:46.607360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e6be0597a4'
down_revision: Union[str, Sequence[str], None] = 'cac93c575368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True, comment='Latitude with 6 decimal places (~11cm precision)'),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True, comment='Longitude with 6 decimal places'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('train_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False, comment='Price multiplier from base fare'),
    sa.Column('amenities', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('station_fee_rules.py',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('per_km_rate', sa.Float(), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=False, comment='UPPER, ORDINARY, SLEEPER, etc.'),
    sa.Column('seat_type', sa.String(length=50), nullable=True, comment='Window, Aisle, etc. if applicable'),
    sa.Column('calculated_distance', sa.Float(), nullable=True),
    sa.Column('surcharge_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('route_stations', sa.Column('station_id', sa.Integer(), nullable=False))
    op.add_column('route_stations', sa.Column('base_fee', sa.Float(), nullable=True, comment='Base fee from route origin to this station'))
    op.add_column('route_stations', sa.Column('fee_per_km', sa.Float(), nullable=True, comment='Additional fee per kilometer from origin'))
    op.add_column('route_stations', sa.Column('is_major_stop', sa.Boolean(), nullable=False, comment='Major stations where train stops longer'))
    op.add_column('route_stations', sa.Column('stop_duration_minutes', sa.Integer(), nullable=True, comment='How long train stops at this station'))
    op.alter_column('route_stations', 'distance_from_origin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Distance in km from route origin',
               existing_nullable=True)
    op.drop_constraint(op.f('route_stations_route_id_fkey'), 'route_stations', type_='foreignkey')
    op.create_foreign_key(None, 'route_stations', 'stations', ['station_id'], ['id'])
    op.create_foreign_key(None, 'route_stations', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.drop_column('route_stations', 'station_name')
    op.drop_column('route_stations', 'station_code')
    op.add_column('routes', sa.Column('fee_calculation_type', sa.String(length=20), nullable=False, comment='FIXED_PER_STATION, PER_KM, ZONE_BASED, HYBRID'))
    op.alter_column('routes', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('routes', 'duration',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('routes', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('routes', 'created_at')
    op.drop_column('routes', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('routes', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('routes', 'duration',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('routes', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('routes', 'fee_calculation_type')
    op.add_column('route_stations', sa.Column('station_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('station_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'route_stations', type_='foreignkey')
    op.drop_constraint(None, 'route_stations', type_='foreignkey')
    op.create_foreign_key(op.f('route_stations_route_id_fkey'), 'route_stations', 'routes', ['route_id'], ['id'])
    op.alter_column('route_stations', 'distance_from_origin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Distance in km from route origin',
               existing_nullable=True)
    op.drop_column('route_stations', 'stop_duration_minutes')
    op.drop_column('route_stations', 'is_major_stop')
    op.drop_column('route_stations', 'fee_per_km')
    op.drop_column('route_stations', 'base_fee')
    op.drop_column('route_stations', 'station_id')
    op.drop_table('station_fee_rules.py')
    op.drop_table('train_classes')
    op.drop_table('stations')
    # ### end Alembic commands ###
