"""21Aug1056ambookingupdates

Revision ID: 734c28accaa3
Revises: ed5829132bdb
Create Date: 2026-08-21 10:57:27.495288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '734c28accaa3'
down_revision: Union[str, Sequence[str], None] = 'ed5829132bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_seat_id'), 'bookings', ['seat_id'], unique=False)
    op.create_index(op.f('ix_bookings_train_id'), 'bookings', ['train_id'], unique=False)
    op.drop_constraint(op.f('bookings_coach_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'coach_id')
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_index(op.f('ix_coaches_train_id'), 'coaches', ['train_id'], unique=False)
    op.drop_column('coaches', 'created_at')
    op.drop_column('coaches', 'updated_at')
    op.create_index(op.f('ix_seats_coach_id'), 'seats', ['coach_id'], unique=False)
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.drop_column('seats', 'created_at')
    op.drop_column('seats', 'updated_at')
    op.drop_column('trains', 'created_at')
    op.drop_column('trains', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('trains', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('seats', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('seats', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_coach_id'), table_name='seats')
    op.add_column('coaches', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('coaches', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_coaches_train_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.add_column('bookings', sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_coach_id_fkey'), 'bookings', 'coaches', ['coach_id'], ['id'])
    op.drop_index(op.f('ix_bookings_train_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_seat_id'), table_name='bookings')
    # ### end Alembic commands ###
