"""added train rider models 1Aug8:46pm

Revision ID: 7ce7f7f81777
Revises: 35fa8ae73753
Create Date: 2026-08-01 20:46:57.653398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce7f7f81777'
down_revision: Union[str, Sequence[str], None] = '35fa8ae73753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
