"""added train rider models 1Aug9:07m

Revision ID: 817759095bf9
Revises: 7ce7f7f81777
Create Date: 2026-08-01 21:09:08.036497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817759095bf9'
down_revision: Union[str, Sequence[str], None] = '7ce7f7f81777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('TRAIN_DRIVER', 'ASSISTANT_DRIVER', 'TRAIN_GUARD', 'TICKET_CHECKER', 'STATION_MASTER', 'STATION_STAFF', 'DISPATCHER', 'MAINTENANCE', 'INSPECTOR', name='staffrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('certification_details', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_DUTY', 'OFF_DUTY', 'ON_LEAVE', 'INACTIVE', name='staffstatus'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_shift_start', sa.DateTime(), nullable=True),
    sa.Column('current_shift_end', sa.DateTime(), nullable=True),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=True)
    op.create_table('staff_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('attendance_type', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'ON_LEAVE', name='attendancetype'), nullable=False),
    sa.Column('location_check_in', sa.String(length=255), nullable=True),
    sa.Column('location_check_out', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_station_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('role_at_station', sa.String(length=50), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='stationassignmentstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_rider_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.Enum('TRAIN_DEVICE', 'STAFF_DEVICE', 'STATION_DEVICE', name='devicetype'), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('current_route_station_id', sa.Integer(), nullable=True),
    sa.Column('next_route_station_id', sa.Integer(), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('is_charging', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_route_station_id'], ['route_stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['next_route_station_id'], ['route_stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_rider_devices_device_id'), 'train_rider_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_train_rider_devices_id'), 'train_rider_devices', ['id'], unique=False)
    op.create_table('train_staff_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('role_on_train', sa.String(length=50), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['train_rider_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_id'), 'location_history', ['id'], unique=False)
    op.create_index(op.f('ix_location_history_timestamp'), 'location_history', ['timestamp'], unique=False)
    op.create_table('staff_shift_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('train_assignment_id', sa.UUID(), nullable=True),
    sa.Column('station_assignment_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_assignment_id'], ['staff_station_assignments.id'], ),
    sa.ForeignKeyConstraint(['train_assignment_id'], ['train_staff_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_arrival_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('route_station_id', sa.Integer(), nullable=False),
    sa.Column('train_stop_id', sa.Integer(), nullable=True),
    sa.Column('schedule_date', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('expected_arrival_time', sa.Time(), nullable=True),
    sa.Column('arrival_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('expected_departure_time', sa.Time(), nullable=True),
    sa.Column('departure_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('stop_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('stop_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('next_route_station_id', sa.Integer(), nullable=True),
    sa.Column('next_station_name', sa.String(length=100), nullable=True),
    sa.Column('expected_next_arrival', sa.DateTime(), nullable=True),
    sa.Column('arrival_latitude', sa.Float(), nullable=True),
    sa.Column('arrival_longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['train_rider_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_route_station_id'], ['route_stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_station_id'], ['route_stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_stop_id'], ['train_stops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_arrival_logs_id'), 'station_arrival_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_arrival_logs_id'), table_name='station_arrival_logs')
    op.drop_table('station_arrival_logs')
    op.drop_table('staff_shift_logs')
    op.drop_index(op.f('ix_location_history_timestamp'), table_name='location_history')
    op.drop_index(op.f('ix_location_history_id'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_table('train_staff_assignments')
    op.drop_index(op.f('ix_train_rider_devices_id'), table_name='train_rider_devices')
    op.drop_index(op.f('ix_train_rider_devices_device_id'), table_name='train_rider_devices')
    op.drop_table('train_rider_devices')
    op.drop_table('staff_station_assignments')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
