"""23Aug5_20pm

Revision ID: 86601fdd7fcd
Revises: 2d89ce5b0e0f
Create Date: 2026-08-23 17:21:02.167160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86601fdd7fcd'
down_revision: Union[str, Sequence[str], None] = '2d89ce5b0e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('from_route_station_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('to_route_station_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bookings_from_route_station_id'), 'bookings', ['from_route_station_id'], unique=False)
    op.create_index(op.f('ix_bookings_to_route_station_id'), 'bookings', ['to_route_station_id'], unique=False)
    op.create_index(op.f('ix_bookings_travel_date'), 'bookings', ['travel_date'], unique=False)
    op.create_foreign_key(None, 'bookings', 'route_stations', ['to_route_station_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'bookings', 'route_stations', ['from_route_station_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_travel_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_to_route_station_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_from_route_station_id'), table_name='bookings')
    op.drop_column('bookings', 'to_route_station_id')
    op.drop_column('bookings', 'from_route_station_id')
    # ### end Alembic commands ###
