"""seat model updated 1Aug3:28pm

Revision ID: 8c2881745763
Revises: dd0e0ba2ba1d
Create Date: 2026-08-01 15:28:15.179301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2881745763'
down_revision: Union[str, Sequence[str], None] = 'dd0e0ba2ba1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
