"""add route_station

Revision ID: 921f15b4cd01
Revises: 79c26b1c37be
Create Date: 2026-07-26 08:19:49.754452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921f15b4cd01'
down_revision: Union[str, Sequence[str], None] = '79c26b1c37be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('distance_from_origin', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('routes', sa.Column('origin', sa.String(length=100), nullable=False))
    op.add_column('routes', sa.Column('destination', sa.String(length=100), nullable=False))
    op.add_column('routes', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('duration', sa.String(length=20), nullable=True))
    op.add_column('routes', sa.Column('base_price', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('routes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schedules', sa.Column('departure_time', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('arrival_time', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schedules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('trains', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('trains', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trains', 'updated_at')
    op.drop_column('trains', 'created_at')
    op.drop_column('schedules', 'updated_at')
    op.drop_column('schedules', 'created_at')
    op.drop_column('schedules', 'arrival_time')
    op.drop_column('schedules', 'departure_time')
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_column('routes', 'status')
    op.drop_column('routes', 'base_price')
    op.drop_column('routes', 'duration')
    op.drop_column('routes', 'distance')
    op.drop_column('routes', 'destination')
    op.drop_column('routes', 'origin')
    op.drop_table('route_stations')
    # ### end Alembic commands ###
