"""add speed to train 1Aug2:35pm

Revision ID: 987e40a4c4d5
Revises: 07b94c3d9c34
Create Date: 2026-08-01 14:35:20.961074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987e40a4c4d5'
down_revision: Union[str, Sequence[str], None] = '07b94c3d9c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trains', 'speed')
    # ### end Alembic commands ###
