"""25Aug10_59am

Revision ID: b00c3078197d
Revises: 9b8c56209015
Create Date: 2026-08-25 10:59:25.048302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b00c3078197d'
down_revision: Union[str, Sequence[str], None] = '9b8c56209015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.String(length=64), nullable=False),
    sa.Column('inspection_event_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=120), nullable=True),
    sa.Column('defect_type', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rail_side', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_from_start_miles', sa.Float(), nullable=True, comment='AI inspection distance from inspection origin in miles'),
    sa.Column('ai_priority', sa.String(length=60), nullable=True),
    sa.Column('ai_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_location_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_location_distance_miles', sa.Float(), nullable=True),
    sa.Column('last_location_proximity', sa.String(length=30), nullable=True),
    sa.Column('location_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'inspection_event_id', name='uq_track_issue_inspection_event')
    )
    op.create_index(op.f('ix_track_issues_ai_priority'), 'track_issues', ['ai_priority'], unique=False)
    op.create_index(op.f('ix_track_issues_assigned_staff_id'), 'track_issues', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_track_issues_inspection_id'), 'track_issues', ['inspection_id'], unique=False)
    op.create_index('ix_track_issues_location', 'track_issues', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_track_issues_status'), 'track_issues', ['status'], unique=False)
    op.create_table('track_issue_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_staff_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=40), nullable=False),
    sa.Column('message_kind', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_to_issue_miles', sa.Float(), nullable=True),
    sa.Column('proximity', sa.String(length=30), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_activity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['track_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_activity_id'], ['track_issue_activities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_issue_activities_activity_type'), 'track_issue_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_track_issue_activities_created_at'), 'track_issue_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_track_issue_activities_issue_id'), 'track_issue_activities', ['issue_id'], unique=False)
    op.alter_column('train_rider_devices', 'current_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Current speed in miles per hour (mph)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train_rider_devices', 'current_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Current speed in miles per hour (mph)',
               existing_nullable=True)
    op.drop_index(op.f('ix_track_issue_activities_issue_id'), table_name='track_issue_activities')
    op.drop_index(op.f('ix_track_issue_activities_created_at'), table_name='track_issue_activities')
    op.drop_index(op.f('ix_track_issue_activities_activity_type'), table_name='track_issue_activities')
    op.drop_table('track_issue_activities')
    op.drop_index(op.f('ix_track_issues_status'), table_name='track_issues')
    op.drop_index('ix_track_issues_location', table_name='track_issues')
    op.drop_index(op.f('ix_track_issues_inspection_id'), table_name='track_issues')
    op.drop_index(op.f('ix_track_issues_assigned_staff_id'), table_name='track_issues')
    op.drop_index(op.f('ix_track_issues_ai_priority'), table_name='track_issues')
    op.drop_table('track_issues')
    # ### end Alembic commands ###
