"""booking model updated 1Aug3:40pm

Revision ID: c8e3a1486f93
Revises: 8c2881745763
Create Date: 2026-08-01 15:40:45.362452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e3a1486f93'
down_revision: Union[str, Sequence[str], None] = '8c2881745763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('nrc', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ticket_no', sa.String(length=50), nullable=False),
    sa.Column('booking_no', sa.String(length=50), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reservation_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('service_fee', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('booking_status', sa.Enum('RESERVED', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'REFUNDED', 'FAILED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('passenger_names', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_no'), 'bookings', ['booking_no'], unique=True)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_ticket_no'), 'bookings', ['ticket_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_ticket_no'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_no'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
