"""Rename type to coach_type in coaches table

Revision ID: cac93c575368
Revises: 921f15b4cd01
Create Date: 2026-07-26 09:45:51.928503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac93c575368'
down_revision: Union[str, Sequence[str], None] = '921f15b4cd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('coaches', sa.Column('rows', sa.Integer(), nullable=False))
    op.add_column('coaches', sa.Column('seats_per_row', sa.Integer(), nullable=False))
    op.add_column('coaches', sa.Column('total_seats', sa.Integer(), nullable=False))
    op.add_column('coaches', sa.Column('order_number', sa.Integer(), nullable=True))
    op.add_column('coaches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('coaches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('coaches_train_id_fkey'), 'coaches', type_='foreignkey')
    op.create_foreign_key(None, 'coaches', 'trains', ['train_id'], ['id'], ondelete='CASCADE')
    op.drop_column('coaches', 'coach_no')
    op.drop_column('coaches', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('coaches', sa.Column('coach_no', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coaches', type_='foreignkey')
    op.create_foreign_key(op.f('coaches_train_id_fkey'), 'coaches', 'trains', ['train_id'], ['id'])
    op.drop_column('coaches', 'updated_at')
    op.drop_column('coaches', 'created_at')
    op.drop_column('coaches', 'order_number')
    op.drop_column('coaches', 'total_seats')
    op.drop_column('coaches', 'seats_per_row')
    op.drop_column('coaches', 'rows')
    op.drop_column('coaches', 'name')
    # ### end Alembic commands ###
