"""seat model updated 1Aug3:20pm

Revision ID: dd0e0ba2ba1d
Revises: 987e40a4c4d5
Create Date: 2026-08-01 15:20:53.292929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0e0ba2ba1d'
down_revision: Union[str, Sequence[str], None] = '987e40a4c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('row_number', sa.Integer(), nullable=False))
    op.add_column('seats', sa.Column('position_in_row', sa.Integer(), nullable=False))
    op.add_column('seats', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('seats', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('seats', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('seats_coach_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'coaches', ['coach_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_coach_id_fkey'), 'seats', 'coaches', ['coach_id'], ['id'])
    op.drop_column('seats', 'updated_at')
    op.drop_column('seats', 'created_at')
    op.drop_column('seats', 'is_active')
    op.drop_column('seats', 'position_in_row')
    op.drop_column('seats', 'row_number')
    # ### end Alembic commands ###
