"""change ( route_station, trian, train_stop, station_fee_rule

Revision ID: e90f0b95bd20
Revises: 127d072376d7
Create Date: 2026-08-01 10:16:09.149931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e90f0b95bd20'
down_revision: Union[str, Sequence[str], None] = '127d072376d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('route_station_id', sa.Integer(), nullable=False),
    sa.Column('expected_arrival_time', sa.Time(), nullable=True),
    sa.Column('expected_departure_time', sa.Time(), nullable=True),
    sa.Column('arrival_buffer_minutes', sa.Integer(), nullable=True),
    sa.Column('departure_buffer_minutes', sa.Integer(), nullable=True),
    sa.Column('stop_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_timed_stop', sa.Boolean(), nullable=False),
    sa.Column('actual_arrival_time', sa.Time(), nullable=True),
    sa.Column('actual_departure_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['route_station_id'], ['route_stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_stops_id'), 'train_stops', ['id'], unique=False)
    op.drop_column('route_stations', 'stop_duration_minutes')
    op.drop_column('route_stations', 'expected_departure_time')
    op.drop_column('route_stations', 'expected_arrival_time')
    op.drop_column('route_stations', 'is_timed_stop')
    op.drop_column('route_stations', 'departure_buffer_minutes')
    op.drop_column('route_stations', 'fee_per_km')
    op.drop_column('route_stations', 'arrival_buffer_minutes')
    op.drop_column('route_stations', 'base_fee')
    op.drop_column('routes', 'frequency_minutes')
    op.drop_column('routes', 'start_time')
    op.add_column('station_fee_rules', sa.Column('train_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'station_fee_rules', 'trains', ['train_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_fee_rules', type_='foreignkey')
    op.drop_column('station_fee_rules', 'train_id')
    op.add_column('routes', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('frequency_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('base_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('arrival_buffer_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('fee_per_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('departure_buffer_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('is_timed_stop', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('route_stations', sa.Column('expected_arrival_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('expected_departure_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('route_stations', sa.Column('stop_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_train_stops_id'), table_name='train_stops')
    op.drop_table('train_stops')
    # ### end Alembic commands ###
