"""7_26_502pm

Revision ID: e9882b083f49
Revises: 61e6be0597a4
Create Date: 2026-07-26 17:09:35.006244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9882b083f49'
down_revision: Union[str, Sequence[str], None] = '61e6be0597a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_fee_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('per_km_rate', sa.Float(), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=False),
    sa.Column('seat_type', sa.String(length=50), nullable=True),
    sa.Column('calculated_distance', sa.Float(), nullable=True),
    sa.Column('surcharge_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_fee_rules_id'), 'station_fee_rules', ['id'], unique=False)
    op.drop_table('station_fee_rules.py')
    op.add_column('route_stations', sa.Column('station_name', sa.String(length=100), nullable=False))
    op.add_column('route_stations', sa.Column('station_code', sa.String(length=10), nullable=True))
    op.alter_column('route_stations', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route_stations', 'distance_from_origin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Distance in km from route origin',
               existing_nullable=True)
    op.alter_column('route_stations', 'base_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Base fee from route origin to this station',
               existing_nullable=True)
    op.alter_column('route_stations', 'fee_per_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Additional fee per kilometer from origin',
               existing_nullable=True)
    op.alter_column('route_stations', 'is_major_stop',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Major stations where train stops longer',
               existing_nullable=False)
    op.alter_column('route_stations', 'stop_duration_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='How long train stops at this station',
               existing_nullable=True)
    op.create_index(op.f('ix_route_stations_id'), 'route_stations', ['id'], unique=False)
    op.add_column('routes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('routes', 'fee_calculation_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='FIXED_PER_STATION, PER_KM, ZONE_BASED, HYBRID')
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.alter_column('stations', 'latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment=None,
               existing_comment='Latitude with 6 decimal places (~11cm precision)',
               existing_nullable=True)
    op.alter_column('stations', 'longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment=None,
               existing_comment='Longitude with 6 decimal places',
               existing_nullable=True)
    op.drop_constraint(op.f('stations_code_key'), 'stations', type_='unique')
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.alter_column('train_classes', 'multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Price multiplier from base fare',
               existing_nullable=False)
    op.drop_constraint(op.f('train_classes_code_key'), 'train_classes', type_='unique')
    op.create_index(op.f('ix_train_classes_code'), 'train_classes', ['code'], unique=True)
    op.create_index(op.f('ix_train_classes_id'), 'train_classes', ['id'], unique=False)
    op.add_column('trains', sa.Column('train_type', sa.String(length=50), nullable=True))
    op.add_column('trains', sa.Column('total_coaches', sa.Integer(), nullable=False))
    op.add_column('trains', sa.Column('capacity', sa.Integer(), nullable=False))
    op.alter_column('trains', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trains', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('trains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('trains_train_no_key'), 'trains', type_='unique')
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_train_no'), 'trains', ['train_no'], unique=True)
    op.drop_constraint(op.f('trains_route_id_fkey'), 'trains', type_='foreignkey')
    op.create_foreign_key(None, 'trains', 'routes', ['route_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trains', type_='foreignkey')
    op.create_foreign_key(op.f('trains_route_id_fkey'), 'trains', 'routes', ['route_id'], ['id'])
    op.drop_index(op.f('ix_trains_train_no'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.create_unique_constraint(op.f('trains_train_no_key'), 'trains', ['train_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('trains', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trains', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trains', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('trains', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trains', 'capacity')
    op.drop_column('trains', 'total_coaches')
    op.drop_column('trains', 'train_type')
    op.drop_index(op.f('ix_train_classes_id'), table_name='train_classes')
    op.drop_index(op.f('ix_train_classes_code'), table_name='train_classes')
    op.create_unique_constraint(op.f('train_classes_code_key'), 'train_classes', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('train_classes', 'multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Price multiplier from base fare',
               existing_nullable=False)
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.create_unique_constraint(op.f('stations_code_key'), 'stations', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('stations', 'longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment='Longitude with 6 decimal places',
               existing_nullable=True)
    op.alter_column('stations', 'latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment='Latitude with 6 decimal places (~11cm precision)',
               existing_nullable=True)
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.alter_column('routes', 'fee_calculation_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='FIXED_PER_STATION, PER_KM, ZONE_BASED, HYBRID')
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_index(op.f('ix_route_stations_id'), table_name='route_stations')
    op.alter_column('route_stations', 'stop_duration_minutes',
               existing_type=sa.INTEGER(),
               comment='How long train stops at this station',
               existing_nullable=True)
    op.alter_column('route_stations', 'is_major_stop',
               existing_type=sa.BOOLEAN(),
               comment='Major stations where train stops longer',
               existing_nullable=False)
    op.alter_column('route_stations', 'fee_per_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Additional fee per kilometer from origin',
               existing_nullable=True)
    op.alter_column('route_stations', 'base_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Base fee from route origin to this station',
               existing_nullable=True)
    op.alter_column('route_stations', 'distance_from_origin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Distance in km from route origin',
               existing_nullable=True)
    op.alter_column('route_stations', 'station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('route_stations', 'station_code')
    op.drop_column('route_stations', 'station_name')
    op.create_table('station_fee_rules.py',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_fare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('per_km_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('class_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='UPPER, ORDINARY, SLEEPER, etc.'),
    sa.Column('seat_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Window, Aisle, etc. if applicable'),
    sa.Column('calculated_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('surcharge_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], name=op.f('station_fee_rules.py_from_station_id_fkey')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('station_fee_rules.py_route_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], name=op.f('station_fee_rules.py_to_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('station_fee_rules.py_pkey'))
    )
    op.drop_index(op.f('ix_station_fee_rules_id'), table_name='station_fee_rules')
    op.drop_table('station_fee_rules')
    # ### end Alembic commands ###
