"""neon12AugonSchedule

Revision ID: ed0590f88a6b
Revises: f86381432364
Create Date: 2026-08-12 12:48:31.220194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0590f88a6b'
down_revision: Union[str, Sequence[str], None] = 'f86381432364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('actual_departure_time', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('actual_arrival_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'actual_arrival_time')
    op.drop_column('schedules', 'actual_departure_time')
    # ### end Alembic commands ###
