"""add_route_id_to_schedules

Revision ID: f17f9cb9eddf
Revises: 245b1322ebef
Create Date: 2026-07-26 17:28:04.823702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17f9cb9eddf'
down_revision: Union[str, Sequence[str], None] = '245b1322ebef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('route_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'schedules', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'route_id')
    # ### end Alembic commands ###
