"""change_duration_to_string

Revision ID: f5ff6f1bf596
Revises: a9cfaa7e78b7
Create Date: 2026-08-01 13:30:58.692278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ff6f1bf596'
down_revision: Union[str, Sequence[str], None] = 'a9cfaa7e78b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
