"""neon11Aug10:45am

Revision ID: f86381432364
Revises: 51667bd2cc94
Create Date: 2026-08-11 10:45:45.602665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f86381432364'
down_revision: Union[str, Sequence[str], None] = '51667bd2cc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'translation_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_messages', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('chat_messages', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('chat_messages', 'translation_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
